language: cpp

common_sources: &all_sources
  - ubuntu-toolchain-r-test
  - llvm-toolchain-xenial-7
  - llvm-toolchain-xenial-6

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: xenial
      addons:
          apt:
              sources: *all_sources
              packages:
                - g++-7
                - cmake
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      compiler: clang
      dist: xenial
      addons:
          apt:
              sources: *all_sources
              packages:
                - clang-7
                - libstdc++-7-dev
                - cmake
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
    - os: linux
      compiler: clang
      dist: xenial
      addons:
          apt:
              sources: *all_sources
              packages:
                - clang-6.0
                - g++-7
                - cmake
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

before_install:
  - eval "${MATRIX_EVAL}"


script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
